version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: winwin-postgres
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - winwin-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-api:
    build: ./auth-api
    container_name: winwin-auth
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://winwin-postgres:5432/appdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      APP_SERVICE_B_URL: http://winwin-data:8081/api/transform
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - winwin-net

  data-api:
    build: ./data-api
    container_name: winwin-data
    ports:
      - "8081:8081"
    networks:
      - winwin-net

networks:
  winwin-net:
    driver: bridge

volumes:
  postgres_data: